### ISSUE TITLE
what is the difference between these dataset?

### ISSUE THREAD

**Issue by qhdqhd** [IDLabMedia/large-lightfields-dataset#1]
Thanks for your nice work!
I want to ask what is the difference between the following dataset?
- Barbershop
   - barbershop_LFCuboid_1mx3mx1m.tar       (16    GB)
   - barbershop_LFSphere_e105cm_d145cm.tar  ( 7.5  GB)
   - barbershop_LFSphere_e110cm_d100cm.tar  (    43MB)
   - barbershop_LFCuboid_8panos.tar         (   172MB)

**Comment by mcourteaux** [comment]
You can check out the paper for more information: https://arxiv.org/abs/2204.09523

8 panos is literally just 8 360° panoramic renders.

In case of a spherical setup:
e stands for elevation,
d stands for diameter

**Comment by qhdqhd** [comment]
Congratulations on the publication of your article. I have read it and appreciate your work. 

I have a doubt, the same scene shoots two sets of data, 100  images with 2048x2048 resolution and 1600 images with  512x512 resolution. Their gpu memory usage and total number of rays are the same, but the light field distribution is different. For NeRF, which set of data works better? It seems that the light field distribution of the second group of data is more uniform? can better results?

**Comment by mcourteaux** [comment]
Well, clearly you trade field-of-view resolution details for spatial detail. This will be of huge impact on reflections, depending on how you model them. If you always rely on the nearest viewpoint to determine the color of a reflective surface, the reflection will be a lot more "jumpy" from view to view. If you have more intermediate views, that reflection will make smaller jumps, and it might be beneficial for certain modelling techniques that you have that spatial detail. For NeRF specifically, I wouldn't know. Haven't numerically evaluated the performance of NeRF myself. This dataset certainly allows you to do that. However, my intuition says that the level of detail in the scene will be important. If you have a lot of fine geometry with many occlusions (occluders and occludees both being made of fine geometry (like treebranches in Zen Garden)), I would expect that having more spatial resolution (so more views) will be helpful to correctly model all the small geometry and how it occludes. If instead, the geometry is very simple, but has very detailed textures, the field-of-view resolution might be more interesting. But really, it would need to be tested to know for sure. The fact that we can do subsampling without averaging out pixels (i.e. to create aliased downsampled input images) is so extremely interesting: the field-of-view resolution *is* lower, but the detail is not really lost, as long as you have enough views with such aliased sampled data.
