### ISSUE TITLE
bad result

### ISSUE THREAD

**Issue by zuixiaosanlang** [IDLabMedia/large-lightfields-dataset#2]
i try this 
![image](https://user-images.githubusercontent.com/20105627/176065078-18bf426e-92c6-477f-9a55-1793f226c9a4.png)

But the result i get, is very bad.  i am missing something???

![image](https://user-images.githubusercontent.com/20105627/176065344-59138859-8cb4-4a38-9edc-1700c79213f6.png)

**Comment by mcourteaux** [comment]
Hi! I'm very sorry for the late reply. I missed any notification of this. I will check notification settings of this repository. Thanks for being interested!

Looking at your result, I can clearly see the correct shape of the building, but it's fuzzed with these blurry specs... Very strange. My first thought is that the conversion of Blender coordinate system of the camera transforms to the NeRF one is somehow broken. Can you try to visualize the cameras in the NeRF "**Debug visualization**" section, under the **Rendering** section. These should yield a sphere, where you can see that all cameras are pointing outward nicely. Can you validate that, and possibly share a screenshot? Make sure you "move backward" enough such that the whole setup of cameras is visible.

We'll figure this out, as I'm actively using NeRF with this dataset in my daily research and all works great for me :)

**Comment by zuixiaosanlang** [comment]
@mcourteaux 
![image](https://user-images.githubusercontent.com/20105627/178184105-5091f9a2-ac0b-4625-84ba-935fc868bbd9.png)

and the transforms.json
![image](https://user-images.githubusercontent.com/20105627/178184245-0e9574eb-e657-407f-8ff1-0972ee5960f8.png)
 anything wrong?

**Comment by mcourteaux** [comment]
Aha, this screenshot was very informative. The scale seems way too big. This surprises me, as the scale was supposed to be a good default, given the `--scene lone_monk` flag. Check this:
https://github.com/IDLabMedia/large-lightfields-dataset/blob/4f01f9c7c561015e8af805c5924afd8b784a53a5/generate_NERF_transforms.py#L149-L153

Passing in `--scene lone_monk` should have set the scale to `0.03`, so maybe you mistyped (or forgot) that flag? Cheers!

**Comment by zuixiaosanlang** [comment]
@mcourteaux 
o, thank you. it is my mistake, i pass the wrong param --scene. 
now , i correct it. But the result is still blurred, I don't know if it's correct
![image](https://user-images.githubusercontent.com/20105627/178641015-0f5436e0-9317-43f9-9ae4-0ef78fd6a9f5.png)

![image](https://user-images.githubusercontent.com/20105627/178641133-07b43b90-26ef-4683-9fd1-73bc2f122f31.png)

![image](https://user-images.githubusercontent.com/20105627/178641253-48c5bbac-93cd-47de-8a83-e961e4396bf3.png)

**Comment by mcourteaux** [comment]
I think this is a limitation of instant-ngp. This result looks quite good to me. Just consider that you are rather far away from the sphere of cameras, so it is expected that results start degrading a little. You could try to double the scale, and increase the `aabb_scale` to 2. For more information, see: https://github.com/NVlabs/instant-ngp/issues/53#issuecomment-1133831791 Alternatively, you could also try with higher resolution images (by increasing the `--scale` parameter during reprojection).
